# Generated by Django 3.1.14 on 2022-04-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JabOffer',
            new_name='JobOffer',
        ),
    ]
